/*global systemDictionary:true */
'use strict';

systemDictionary = {
  "NexoWattVPN": { "en": "NexoWattVPN", "de": "NexoWattVPN" },
  "Grundkonfiguration": { "en": "Base configuration", "de": "Grundkonfiguration" },
  "Endpoint Host (DDNS / Public IP)": { "en": "Endpoint host (DDNS / Public IP)", "de": "Endpoint Host (DDNS / Public IP)" },
  "Port": { "en": "Port", "de": "Port" },
  "AllowedIPs Mode": { "en": "AllowedIPs mode", "de": "AllowedIPs Modus" },
  "Host-only (nur VPN-Server-IP)": { "en": "Host-only (only VPN server IP)", "de": "Host-only (nur VPN-Server-IP)" },
  "Custom": { "en": "Custom", "de": "Benutzerdefiniert" },
  "AllowedIPs Custom": { "en": "AllowedIPs custom", "de": "AllowedIPs benutzerdefiniert" },
  "DNS 1 (optional)": { "en": "DNS 1 (optional)", "de": "DNS 1 (optional)" },
  "DNS 2 (optional)": { "en": "DNS 2 (optional)", "de": "DNS 2 (optional)" },
  "Firewall / Port-Restriktion (Interface wg0)": { "en": "Firewall / port restriction (wg0)", "de": "Firewall / Port-Restriktion (Interface wg0)" },
  "Service-Ports (TCP)": { "en": "Service ports (TCP)", "de": "Service-Ports (TCP)" },
  "Customer-Ports (TCP)": { "en": "Customer ports (TCP)", "de": "Customer-Ports (TCP)" },
  "Auto Firewall anwenden": { "en": "Auto apply firewall", "de": "Auto Firewall anwenden" },
  "Firewall anwenden": { "en": "Apply firewall", "de": "Firewall anwenden" },
  "Firewall entfernen": { "en": "Remove firewall", "de": "Firewall entfernen" },
  "Aktionen": { "en": "Actions", "de": "Aktionen" },
  "Status aktualisieren": { "en": "Refresh status", "de": "Status aktualisieren" },
  "Konfiguration anwenden": { "en": "Apply configuration", "de": "Konfiguration anwenden" },
  "Peers laden": { "en": "Load peers", "de": "Peers laden" },
  "Peers / Profile": { "en": "Peers / profiles", "de": "Peers / Profile" },
  "Peer-Name": { "en": "Peer name", "de": "Peer-Name" },
  "Rolle": { "en": "Role", "de": "Rolle" },
  "Service": { "en": "Service", "de": "Service" },
  "Customer": { "en": "Customer", "de": "Customer" },
  "Peer erstellen": { "en": "Create peer", "de": "Peer erstellen" },
  "Deaktivieren": { "en": "Disable", "de": "Deaktivieren" },
  "Aktivieren": { "en": "Enable", "de": "Aktivieren" },
  "Entfernen": { "en": "Remove", "de": "Entfernen" },
  "Config anzeigen": { "en": "Show config", "de": "Config anzeigen" },
  "QR anzeigen": { "en": "Show QR", "de": "QR anzeigen" },
  "Peer-Liste": { "en": "Peer list", "de": "Peer-Liste" },
  "Peer-Config": { "en": "Peer config", "de": "Peer-Config" },
  "QR Code": { "en": "QR code", "de": "QR Code" },
  "Log": { "en": "Log", "de": "Log" }
};
